dod:
  - 'Meaningful title and valuable description in pull request'
  - 'Code change tested manually if not covered by automated tests'
  - 'Pull request linked to one or more issues/stories'
  - 'Acceptance criteria of the linked stories satisfied'
  - 'State of target branch maintained or improved after the code change'
  - '➡️Agreed software engineering best practices upheld'
  - 'Code change comprehended by those who approved it'
